export const BAD_REQUEST = "BAD_REQUEST";
export const CONFLICT = "CONFLICT";
export const NOT_FOUND = "NOT_FOUND";
export const METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";
